[mysqld]
basedir=C:/Program Files/mysql-8.1.13-winx64
datadir=C:/Program Files/mysql-8.1.13-winx64/data
port=3306
max_connections=200
max_connect_errors=10
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default-storage-engine=INNODB
default-authentication-plugin=mysql_native_password

[mysql]
default-character-set=utf8mb4

[client]
port=3306
default-character-set=utf8mb4
